### ISSUE TITLE
Fails to launch ( line 218, in stop     if self._running.is_set():  AttributeError: 'NoneType' object has no attribute 'is_set')

### ISSUE THREAD

**Issue by p2phuture** [peplin/pygatt#128]
I cannot get pyGATT to run in Spyder (Ubuntu 16.04)

I copy the example text on the GitHub page inot a new file, change the device and characteristic identifiers and run it (using GATTTOOL backend)

I get the following errors:

raise NotificationTimeout()

NotificationTimeout: None

**Comment by peplin** [comment]
The particular `AttributeError` in the title is fixed in 400aed9 but I don't think that is your problem (it is a side effect of a thread exiting early). It's worth trying again from `master` to see if this is fixed. If you can provide more information (see the README for how to collect debugging information) that would help!
