### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by Ge0rges** [peplin/pygatt#241]
Does pygatt support macOS? It seems like it requires "gatttool" which is a linux thing. Anyway to make this work on macOS?

**Comment by peplin** [comment]
That's correct, `GATTTOOL` backend supports Linux only (and `gatttool` is deprecated, so the lifespan of that backend is limited: #112). The BGAPI backend may work in MacOS, but since I don't have a Mac to test on I can't say it's officially supported. If you want to try that, do note the hardware requirements in the README.
